# Generated by Django 2.2.4 on 2019-08-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190819_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['blog_id'], 'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
    ]
